site_name: strapi-client
site_url: https://roslovets-inc.github.io/strapi-client/
site_author: Pavel Roslovets

# Repository
repo_name: strapi-client
repo_url: https://github.com/Roslovets-Inc/strapi-client
docs_dir: docs
edit_uri: ""
site_dir: .site

theme:
  name: readthedocs
  logo: img/logo.png
  locale: en

plugins:
  - search
  - awesome-nav
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_root_full_path: false
            show_object_full_path: false
            separate_signature: true
            members_order: source
            inherited_members: true
            extensions:
              - griffe_pydantic

markdown_extensions:
  - nl2br
